// About: what the site does, where its data comes from, and how to report a
// problem.

import {
    breadcrumbs, clear, el, formatDay, modList, PROBLEM_REPORT_BASE,
} from '../lib.js';

const MOD_REPO_URL = 'https://github.com/wispborne/StarsectorModRepo';
const SCRAPER_URL = 'https://github.com/wispborne/Mod_Repo_Scraper';
const WISP_URL = 'https://github.com/wispborne';
const QBMBAMM_URL = 'https://github.com/theRoastSuckling/QBMBAMM';

// GitHub's mark, drawn here since the site loads nothing from anywhere else.
// It takes the colour of the button's words.
const GITHUB_ICON = '<svg viewBox="0 0 24 24" width="1em" height="1em" '
    + 'fill="currentColor" focusable="false" aria-hidden="true"><path d="'
    + 'M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.1'
    + '13.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-'
    + '4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.'
    + '084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 '
    + '3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5'
    + '.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1'
    + '.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .4'
    + '05 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.76'
    + '5.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.'
    + '096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.5'
    + '65 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12'
    + '"/></svg>';

export async function render(root) {
    let collectedOn = null;
    try {
        collectedOn = (await modList()).generatedAt;
    } catch {
        collectedOn = null;
    }

    document.title = 'About | Starmodder';
    clear(root);
    root.append(breadcrumbs([{label: 'About'}]));
    root.append(el('div', {class: 'stack'}, [
        el('div', {class: 'page-head'}, [
            el('h1', {text: 'About Starmodder'}),
        ]),

    section('What this is', [
      'Starmodder brings together Starsector mods posted on the Starsector '
        + 'forum and the Unofficial Starsector Discord.',
      'The site is read-only. It has no accounts, comments, or ratings. Your '
        + 'browser builds each page from files on this site, and nothing you '
        + 'do here is sent anywhere.',
    ]),

    section('Who made this?', [
      [
        'Starmodder is made and maintained by ',
        githubLink(WISP_URL, 'Wisp'),
        '. Its scraper combines code written by Wisp with a Dart port and fork of ',
        githubLink(QBMBAMM_URL, 'QBMBAMM'),
        ', originally made by theRoastSuckling aka kyuubi_.',
      ],
    ]),

    section('Where the data comes from', [
            [
                githubLink(SCRAPER_URL, 'A program'),
                ' collects mod information from forum threads and Discord mod '
                + 'channels, then combines it into ',
                githubLink(MOD_REPO_URL, 'one list'),
                '. Mod names, descriptions, pictures, downloads, and changelogs come '
                + 'from the authors\' posts. Links still point to the places where '
                + 'the authors shared them.',
            ],
            collectedOn
                ? `The site updates twice a day. This data was collected ${
                    formatDay(collectedOn)}.`
                : 'The site updates twice a day.',
            [
                'The published data is available in the ',
                githubLink(MOD_REPO_URL, 'Starsector Mod Repo'),
                '. The code that collects and builds it is in the ',
                githubLink(SCRAPER_URL, 'Mod Repo Scraper'),
                '. Both projects are on GitHub.',
            ],
        ]),

        section('What "AI" means here', [
            'A language model writes a one-sentence summary of each mod based on its '
            + 'forum post. The site can show this summary when the author did not '
            + 'provide a short description. AI summaries have a sparkle icon and '
            + 'a note saying that they were generated by AI.',
            'You can control these summaries under "Show AI mod summaries" in '
            + 'Settings. The default, "Only if missing," uses the author\'s '
            + 'description when one is available. If a mod has both kinds of '
            + 'summary, you can point at the author\'s summary to see the AI one.',
            '"Always" shows the AI summary first whenever one is available. A mod '
            + 'page shows its AI summary between About and Screenshots for either '
            + 'enabled choice.',
            '"Never" hides AI summaries everywhere, including when you point at '
            + 'an author\'s summary. A mod with no other description will then '
            + 'have no summary.',
            'Your choice is saved in your browser for future visits.',
            'The language model also finds details in each post, such as the mod '
            + 'version, changelog, license, and source code link. It copies these '
            + 'details from the post instead of writing new ones.',
        ]),

        section('How updates are detected', [
            'A new release means that a mod\'s version has increased. A reply to its '
            + 'forum thread does not count as a release.',
            'Version numbers can be hard to read reliably from a post, so the site '
            + 'checks them before adding a release to the feed. The same new '
            + 'version must appear in two consecutive checks. A confirmed version '
            + 'cannot move backward. The site ignores a number that matches the Starsector '
            + 'version, since that is probably the game version rather than the '
            + 'mod version. If the thread title includes a version, the detected '
            + 'version must agree with it.',
            'The first confirmed version of a mod is its starting point, so it is '
            + 'not announced as a new release.',
        ]),

        el('p', {}, [
            el('a', {
                class: 'btn',
                href: 'updates.xml',
                text: 'Feed',
            }),
            el('span', {text: ' '}),
            // The site's own code.
            el('a', {
                class: 'btn btn-with-icon',
                href: SCRAPER_URL,
                target: '_blank',
                rel: 'noopener',
            }, [
                el('span', {class: 'github-icon', html: GITHUB_ICON}),
                'GitHub',
            ]),
            el('span', {text: ' '}),
            el('a', {
                class: 'btn btn-primary',
                href: PROBLEM_REPORT_BASE,
                target: '_blank',
                rel: 'noopener nofollow',
                text: 'Report a problem',
            }),
        ]),
    ]));
}

function section(title, paragraphs) {
    return el('section', {class: 'panel'}, [
        el('h2', {text: title}),
        ...paragraphs.map((content) => el(
            'p',
            {class: 'about-line'},
            typeof content === 'string' ? [content] : content,
        )),
    ]);
}

function githubLink(href, text) {
    return el('a', {
        href,
        target: '_blank',
        rel: 'noopener',
        text,
    });
}
