// About: where this comes from, how often, what the AI does, and how to get
// something fixed.
//
// A reader — and more to the point, a mod author who finds their mod listed
// here — needs one page that answers all of that plainly.

import {
  breadcrumbs, clear, el, formatDay, modList, PROBLEM_REPORT_BASE,
} from '../lib.js';

export async function render(root) {
  let collectedOn = null;
  try {
    collectedOn = (await modList()).generatedAt;
  } catch {
    collectedOn = null;
  }

  document.title = 'About — Starmodder';
  clear(root);
  root.append(breadcrumbs([{ label: 'About' }]));
  root.append(el('div', { class: 'stack' }, [
    el('div', { class: 'page-head' }, [
      el('h1', { text: 'About Starmodder' }),
      el('span', {
        class: 'sub',
        text: 'What this is and where the data comes from.',
      }),
    ]),

    section('What this is', [
      'Starmodder lists every Starsector mod posted on the Starsector forum '
        + 'and the Unofficial Starsector Discord, in one place.',
      'It is read-only. There are no accounts, no comments and no ratings. '
        + 'Nothing you do here is sent anywhere — every page is built in your '
        + 'own browser from a few files on this site.',
    ]),

    section('Where the data comes from', [
      'A program reads the mod threads on the forum and the mod channels on '
        + 'Discord, and puts the two together. Nothing here is written by us: '
        + 'the names, descriptions, '
        + 'pictures, downloads and changelogs are the authors\' own words and '
        + 'files, and every link goes to where they put them.',
      collectedOn
        ? `It runs twice a day. The data on show was collected ${
          formatDay(collectedOn)}.`
        : 'It runs twice a day.',
    ]),

    section('What "AI" means here', [
      'Where a mod\'s post has no short description in it, a language model is '
        + 'asked to write one sentence from the post. Those, and only those, '
        + 'carry a sparkle before the words and a line underneath saying '
        + 'they were generated by AI.',
      'Pick "Never show them" under Summaries in Settings and they '
        + 'disappear. A mod whose only description was that sentence then '
        + 'reads as having none. The choice is kept in your browser and '
        + 'holds between visits.',
      'The same model also picks facts out of a post: the mod version, the '
        + 'changelog, the license, and where the code is kept. Those are '
        + 'copied from the post, not written.',
    ]),

    section('Getting told about new releases', [
      'Every new release shows up on the home page, and the same list is '
        + 'written out as a feed file any feed reader can follow. Nothing is '
        + 'sent to you and nothing about you is collected — a feed reader asks '
        + 'this site for the file, the same way your browser asks for a page.',
    ]),

    section('How releases are worked out', [
      'A release means a mod\'s version actually moved forward — not that '
        + 'somebody replied to its thread.',
      'The version is read off the post, and the reading is noisy, so four '
        + 'rules stand between it and the feed. A reading has to hold for two '
        + 'runs before it is believed. A believed version never moves '
        + 'backwards. A version that matches the game\'s own version is thrown '
        + 'out, because the two get confused. And where the thread title names '
        + 'a version, a new version that disagrees with it is dropped.',
      'The first version we ever believe for a mod is never announced as a '
        + 'release, or every mod would be announced at once the day it was '
        + 'first seen.',
    ]),

    el('p', {}, [
      el('a', {
        class: 'btn',
        href: 'updates.xml',
        text: 'The release feed',
      }),
      el('span', { text: ' ' }),
      el('a', {
        class: 'btn btn-primary',
        href: PROBLEM_REPORT_BASE,
        target: '_blank',
        rel: 'noopener nofollow',
        text: 'Report a problem',
      }),
    ]),
  ]));
}

function section(title, paragraphs) {
  return el('section', { class: 'panel' }, [
    el('h2', { text: title }),
    ...paragraphs.map((text) => el('p', { class: 'about-line', text })),
  ]);
}
